### ISSUE TITLE
Tool to integrate

### ISSUE THREAD

**Issue by sagar87** [sagar87/spatialproteomics#34]
Keep on adding to the list:

## Segmentation tools / Preprocessing
- [x] Mesmer
- [ ] ilastik
- [ ] Baysor
- [ ] McMicro tools (if standalone versions are available)

## Cell phenotyping (not a big fan of those but we're inclusive)
- [ ] Celesta
- [ ] Stellar 

## Importing
- [x] read from spatialdata directly

**Comment by sagar87** [comment]
Why Leiden ? That's `anndata` terretory.

**Comment by MeyerBender** [comment]
Fair enough, will remove again

**Comment by MeyerBender** [comment]
Implemented Mesmer in #46

**Comment by MeyerBender** [comment]
Some issues with the following tools: 
- Ilastik: if running in headless mode, we'd need to call it as subprocess, see [here](https://forum.image.sc/t/how-to-call-and-run-ilastik-from-python/22009)
- Baysor: implemented in Julia, would also need to run headless, see [here](https://github.com/kharchenkolab/Baysor)
- CELESTA: implemented in R, would once again need to think about how to incorporate this. 

We currently have stardist, cellpose and Mesmer, I would argue those three might already be enough on the segmentation front?

Will continue to implement Stellar for now, as it is the only remaining python package from the list.

**Comment by MeyerBender** [comment]
Tools in the top here are not really relevant to the problems we are trying to solve. Some more tools I want to look into however: `Segger`, `instanSeg`.

**Comment by MeyerBender** [comment]
Both of these are not currently in a usable state. For the other tools, sufficient reasons have been given not to incorporate them for now. Closing this issue, new feature requests should be submitted with individual issues.
