### ISSUE TITLE
pp["DAPI"] is dependent on obs

### ISSUE THREAD

**Issue by MeyerBender** [sagar87/spatialproteomics#39]
In the `pp.filter_by_obs` method, it looks like the centroids get lost, which causes downstream issues when trying to select by a marker. Needs further investigation to find the root cause (`pp["DAPI"]` should not be dependent on `obs` in the first place) and a proper fix.
```
# does not work
img_resegmented.pp.add_observations('area').pp.filter_by_obs('area', func=lambda x: (x > 50) & (x < 300)).pp['DAPI']
# works
img_resegmented.pp.add_observations('area').pp.filter_by_obs('area', func=lambda x: (x > 50) & (x < 300)).pp.add_observations().pp['DAPI']
```

**Comment by sagar87** [comment]
Smells like some evil inplace operations....

**Comment by sagar87** [comment]
Hold on, that works: 

![2024-05-28 at 14 00](https://github.com/sagar87/spatialproteomics/assets/7542594/9ca8d4ea-dd33-4375-afec-af07a701ea64)

**Comment by MeyerBender** [comment]
But it doesn't if you remove the centroids, correct? The issue is in the `pp.get_bbox(x_slice, y_slice)`, I think because without centroids cells can't be selected by the FOV. Seems like a bug in `__getitem__` to me.

**Comment by MeyerBender** [comment]
Scratch that, the issue is in `get_bbox`, where `Dims.CELLS in self._obj.sizes` is true and triggers a subsetting of cells, which is impossible. Can probably fix by checking if there are centroids present, and if not, we simply do not subset the cells. What do you think?

**Comment by MeyerBender** [comment]
Actually there's a simpler fix, the obs simply did not get computed in the `cellpose` method, just implementing that should fix it.

**Comment by MeyerBender** [comment]
One thing to keep in mind is that with cellpose we can have either a segmentation on one or multiple channels. If we only have one channel it's fine, but with multiple channels we would need to specify which of the channels takes priority (could just do the first one but that would be more of a temporary fix). Basically we can't sync `obs` with a multidimensional segmentation mask.

**Comment by MeyerBender** [comment]
Honestly I'm not the biggest fan of having to call `pp.add_segmentation()` after segmenting, seems a bit redundant, especially since you already have `key_added` as a parameter. But it is probably the most explicit solution, so I guess it'll get the job done. Can you also implement this in `stardist` and add it to the docs then?
